### ISSUE TITLE
brainflow data acquisition

### ISSUE THREAD

**Issue by khashdroid** [MindRove/SDK_Public#1]
Hi there,
great work on the headset!

I am using the brainflow libraries provided by mindrove. I set the board_id=16 (mindrove wifi headset). The board connects and starts streaming data. However, I have a few questions about the data itself.
1. brainflow reports 8 eeg channels ([0,1,2,3,4,5,6,7]). Shouldn't it be 6 eeg channels?
2. data from channel 3 is always zero. so I'm wondering if I'm doing something wrong here or if there's a bug in the DLL/lib files.
I used the following parameters/routines:
board_id=16
                sampling_rate = BoardShim.get_sampling_rate(board_id)  --> returns 500
                eeg_channels = BoardShim.get_eeg_channels(board_id) --> returns 8
                data = board_shim.get_board_data()
example of a sample of data I'm getting: [29.0,18.0,43.0,0.0,78.0,116.0,0.0,77.0]

and I get the following channel id's & parameters using brainflow's functions:

eeg channels: [0, 1, 2, 3, 4, 5, 6, 7]
package num channel: 26
battery channel: 18
num rows: 28
timestamp channel: 27
gyro channels: [20, 21, 22, 23, 24, 25]

Thanks in advance :)

**Comment by rokaijano** [comment]
Hi! 
Yes, indeed, there are 6 EEG channels on the wifi headset. 
The indexes of 3 and 6 are additional, currently not-in-use channels: they will be put on the "other_channels" section in the next commit. 
Please let me know if the next commit will solve the problem. 
Thanks!

**Comment by rokaijano** [comment]
Hi!
Yes, indeed, there are 6 EEG channels on the wifi headset.
Two channels are currently not-in-use channels: they will be put on the "other_channels" section in the next commit.
Please let me know if the next commit will solve the problem.
Thanks!

**Comment by khashdroid** [comment]
Thanks for the fix!
now I'm getting the following results:
other channels --> [3, 6, 19]
eeg channels --> [0, 1, 2, 4, 5, 7]
so, now I see 6 eeg channels streaming data. so, that seems to be fine now.

another thing, the eeg data values coming from the brainflow driver look a bit strange (e.g. the zip file attached here), it seems very jumpy (sometimes the signals look like a binary step function when plotted) and it seems like values are duplicated in successive samples. 
However, the data looks ok when I use the Mindrove GUI app
[Mindrove_brainflow_1000_samples.zip](https://github.com/MindRove/SDK_Public/files/5642791/Mindrove_brainflow_1000_samples.zip)

**Comment by rokaijano** [comment]
I pushed another version, you should get eeg_channels with indexed up to 6 and the correct values.
Please check and if the issue still persists, I will reopen the issue.

**Comment by khashdroid** [comment]
from what I see the issue is resolved now and I'm getting more reasonable eeg data. Thanks! (seemed like a data-type interpretation issue, probably from the datahandler.dll file or wherever the raw eeg bytestream is converted into decimal values).
